"""
export_onnx.py — Export LightGBM win_loss model to ONNX + scaler parameters.

Outputs:
  ML/outputs/research_v2/deploy/ICT_ATLAS_LGB_winloss_v2.onnx
  ML/outputs/research_v2/deploy/scaler_params.csv   (mean/std per feature)
  ML/outputs/research_v2/deploy/feature_order.txt   (feature names in array order)
  ML/outputs/research_v2/deploy/validation_cases.csv (100 test cases for MQL5 verification)

Usage:
    python ML/scripts/export_onnx.py
"""

import sys
import json
from pathlib import Path

import numpy as np
import pandas as pd
import joblib

sys.path.insert(0, str(Path(__file__).parent.parent))

MODEL_PATH  = Path(__file__).parent.parent / "outputs" / "research_v2" / "models" / "LightGBM_win_loss.pkl"
DATA_PATH   = Path(__file__).parent.parent / "data" / "ICT_ATLAS_Research_Signals_Labeled_v2.csv"
DEPLOY_DIR  = Path(__file__).parent.parent / "outputs" / "research_v2" / "deploy"


def load_bundle():
    with open(MODEL_PATH, "rb") as f:
        return joblib.load(f)


def export_onnx(model, scaler, feature_names, deploy_dir):
    """Export LightGBM model to ONNX format."""
    try:
        from onnxmltools import convert_lightgbm
        from onnxmltools.convert.common.data_types import FloatTensorType
    except ImportError:
        print("  onnxmltools not available — skipping ONNX export")
        return None

    n_features = len(feature_names)
    initial_type = [("float_input", FloatTensorType([None, n_features]))]

    onnx_model = convert_lightgbm(
        model, "LightGBM_winloss_v2",
        initial_types=initial_type,
        target_opset=12,
    )

    onnx_path = deploy_dir / "ICT_ATLAS_LGB_winloss_v2.onnx"
    with open(onnx_path, "wb") as f:
        f.write(onnx_model.SerializeToString())

    print(f"  ✓ ONNX model saved: {onnx_path.name}  ({onnx_path.stat().st_size / 1024:.0f} KB)")
    return onnx_path


def export_scaler(scaler, feature_names, deploy_dir):
    """Export StandardScaler mean/std to CSV for MQL5 constant arrays."""
    params = pd.DataFrame({
        "feature":    feature_names,
        "index":      range(len(feature_names)),
        "mean":       scaler.mean_,
        "std":        scaler.scale_,
    })
    path = deploy_dir / "scaler_params.csv"
    params.to_csv(path, index=False)
    print(f"  ✓ Scaler params saved: {path.name}  ({len(params)} features)")
    return params


def export_feature_order(feature_names, deploy_dir):
    """Write feature order file for MQL5 array alignment."""
    path = deploy_dir / "feature_order.txt"
    with open(path, "w") as f:
        for i, name in enumerate(feature_names):
            f.write(f"{i:2d}  {name}\n")
    print(f"  ✓ Feature order saved: {path.name}")


def export_validation_cases(model, scaler, X, df, feature_names, deploy_dir, n=200):
    """Export test cases with known Python outputs for MQL5 verification."""
    X_s = scaler.transform(X)
    proba = model.predict_proba(X_s)[:, 1]

    # Sample n rows evenly across score distribution
    idx = np.argsort(proba)
    step = max(1, len(idx) // n)
    sample_idx = idx[::step][:n]

    cases = X.iloc[sample_idx].copy()
    cases["expected_score"] = proba[sample_idx]
    cases["win_loss"]       = df["win_loss"].values[sample_idx]

    path = deploy_dir / "validation_cases.csv"
    cases.to_csv(path, index=False)
    print(f"  ✓ Validation cases saved: {path.name}  ({len(cases)} rows, full score range)")


def validate_onnx(onnx_path, model, scaler, X):
    """Check ONNX outputs match Python outputs on test set."""
    try:
        import onnxruntime as rt
    except ImportError:
        print("  onnxruntime not available — skipping ONNX validation")
        return

    X_s = scaler.transform(X).astype(np.float32)
    sess = rt.InferenceSession(str(onnx_path))
    input_name = sess.get_inputs()[0].name

    # Run on first 500 rows
    n = min(500, len(X_s))
    onnx_out   = sess.run(None, {input_name: X_s[:n]})[1]   # probabilities output
    python_out = model.predict_proba(scaler.transform(X.iloc[:n]))[:, 1]

    # Extract class-1 probability from ONNX dict output
    if isinstance(onnx_out[0], dict):
        onnx_proba = np.array([row[1] for row in onnx_out])
    else:
        onnx_proba = np.array(onnx_out)[:, 1] if onnx_out.ndim == 2 else np.array(onnx_out)

    max_diff = np.abs(onnx_proba - python_out).max()
    mean_diff = np.abs(onnx_proba - python_out).mean()
    print(f"  ✓ ONNX validation: max diff={max_diff:.6f}  mean diff={mean_diff:.6f}  "
          f"{'PASS' if max_diff < 0.001 else 'WARN — check ONNX conversion'}")


def print_mql5_constants(params):
    """Print MQL5-ready constant arrays for the EA."""
    print("\n  // Paste into ICT_ATLAS_EA_V1.1.mq5 (feature scaling constants):")
    print("  // Generated by export_onnx.py — do not edit manually")
    print(f"  const int    ML_N_FEATURES = {len(params)};")
    means = ", ".join(f"{v:.6f}" for v in params["mean"])
    stds  = ", ".join(f"{v:.6f}" for v in params["std"])
    names = ", ".join(f'"{n}"' for n in params["feature"])
    print(f"  const double ML_FEATURE_MEAN[] = {{{means}}};")
    print(f"  const double ML_FEATURE_STD[]  = {{{stds}}};")
    print(f"  // Feature order: {{{names}}}")


def strip_zipmap(onnx_path):
    """Remove the ZipMap node from an ONNX model for MT5 compatibility.

    The ZipMap node converts numeric probability outputs into a list of dicts,
    which MT5's ONNX runtime does not support.  This function strips it and
    rewires the graph so the model outputs raw int64 labels and float32
    probability arrays instead.

    Parameters
    ----------
    onnx_path : pathlib.Path
        Path to the ONNX model file to strip.
    """
    try:
        import onnx
        import onnx.helper as helper
        from onnx import TensorProto
        import onnxruntime as rt
        import numpy as np
    except ImportError as exc:
        print(f"  strip_zipmap: skipping — required package not available ({exc})")
        return

    # Load model
    model = onnx.load(str(onnx_path))
    graph = model.graph

    # Locate and remove the ZipMap node
    zipmap_nodes = [n for n in graph.node if n.op_type == "ZipMap"]
    if not zipmap_nodes:
        print("  strip_zipmap: no ZipMap node found — model may already be stripped")
    for node in zipmap_nodes:
        graph.node.remove(node)

    # Rebuild outputs: label (int64, [1]) and lgbmprobabilities (float, [None, 2])
    del graph.output[:]
    label_output = helper.make_tensor_value_info("label", TensorProto.INT64, [1])
    prob_output  = helper.make_tensor_value_info("lgbmprobabilities", TensorProto.FLOAT, [None, 2])
    graph.output.extend([label_output, prob_output])

    # Validate graph structure
    onnx.checker.check_model(model)

    # Save stripped model
    out_path = onnx_path.parent / f"{onnx_path.stem}_mt5.onnx"
    with open(out_path, "wb") as f:
        f.write(model.SerializeToString())

    # Validate stripped model vs original on 100 synthetic float32 rows
    rng = np.random.default_rng(42)
    X_val = rng.standard_normal((100, 48)).astype(np.float32)

    sess_orig     = rt.InferenceSession(str(onnx_path))
    sess_stripped = rt.InferenceSession(str(out_path))

    input_name = sess_orig.get_inputs()[0].name

    orig_out     = sess_orig.run(None, {input_name: X_val})
    stripped_out = sess_stripped.run(None, {input_name: X_val})

    # Original model returns dict probabilities; extract class-1 float array
    orig_proba = orig_out[1]
    if isinstance(orig_proba[0], dict):
        orig_proba = np.array([[row[0], row[1]] for row in orig_proba], dtype=np.float32)
    else:
        orig_proba = np.array(orig_proba, dtype=np.float32)

    stripped_proba = np.array(stripped_out[1], dtype=np.float32)

    max_diff = float(np.abs(orig_proba - stripped_proba).max())
    assert max_diff < 1e-6, f"strip_zipmap validation failed: max diff={max_diff:.2e}"

    print(f"  strip_zipmap saved: {out_path}  (max diff vs original={max_diff:.2e})")


def run():
    DEPLOY_DIR.mkdir(parents=True, exist_ok=True)

    print("\n" + "="*60)
    print(" ICT ATLAS EA V1.1 — ONNX Export")
    print("="*60)

    print("\n[1/5] Loading model bundle ...")
    bundle = load_bundle()
    model  = bundle["model"]
    scaler = bundle["scaler"]

    print("\n[2/5] Building feature matrix ...")
    from run_research_pipeline import build_features
    df = pd.read_csv(DATA_PATH)
    X  = build_features(df)
    feature_names = list(X.columns)
    print(f"  {len(df):,} signals | {len(feature_names)} features")

    print("\n[3/5] Exporting ONNX model ...")
    onnx_path = export_onnx(model, scaler, feature_names, DEPLOY_DIR)

    print("\n[4/5] Exporting scaler parameters ...")
    params = export_scaler(scaler, feature_names, DEPLOY_DIR)
    export_feature_order(feature_names, DEPLOY_DIR)

    print("\n[5/5] Exporting validation cases ...")
    export_validation_cases(model, scaler, X, df, feature_names, DEPLOY_DIR)

    if onnx_path:
        print("\n  Validating ONNX output against Python ...")
        validate_onnx(onnx_path, model, scaler, X)
        print("\n  Stripping ZipMap for MT5 compatibility ...")
        strip_zipmap(onnx_path)

    print_mql5_constants(params)

    print("\n" + "="*60)
    print(f" Deployment artefacts saved to: {DEPLOY_DIR.resolve()}")
    print("="*60)
    print("\n  Files:")
    for f in sorted(DEPLOY_DIR.iterdir()):
        print(f"    {f.name:45s} {f.stat().st_size/1024:8.1f} KB")


if __name__ == "__main__":
    run()
